tracer.property: "I AM THE DEFAULT"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform: "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://localhost:5432/eagle_eye_local"
spring.datasource.username: "{cipher}504e80802a7d7c2db7044d76486bf4823af01739f7fd1e9187927adf9b1277fe"
spring.datasource.password: "{cipher}f1e04b0b63455234f4955c83af6db28272d4fc179fe43171c062102332445289c61fb349339833427f886ecd46749009"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
spring.jpa.hibernate.ddl-auto: update
